In [1]:
import sys, os, json, math, re, shapely, pickle, dotenv, base64, requests, rasterio, sknw
sys.path.append('backend/app/')
import xarray as xr, numpy as np, geopandas as gpd
import pandas as pd, dask.array as da
from Functions import functions, gridFunctions, flowFunctions
import matplotlib.pyplot as plt
from datetime import datetime
from rasterio.features import shapes
from shapely.geometry import shape, LineString, Point
from skimage.morphology import skeletonize
from requests.auth import HTTPBasicAuth

In [2]:
dotenv.load_dotenv()
url = os.getenv('NVE_URL')
client_id = os.getenv('NVE_API_KEY')

In [ ]:
headers = {'Accept': 'application/json', "X-API-Key": client_id}
new_url = f'{url}/Stations'
r = requests.get(
    new_url, headers=headers
)
columns = ['stationId', 'stationName', 'latitude', 'longitude', 'councilName', 'countyName']
df = pd.DataFrame(r.json()['data'])[columns]
df

,stationId,stationName,latitude,longitude,utmEast_Z33,utmNorth_Z33,masl,riverName,councilNumber,councilName,...,culQ5,culQ10,culQ20,culQ50,culHm,culH5,culH10,culH20,culH50,seriesList
0,1.15.0,Femsjø,59.13015,11.48516,298887,6559841,81,Haldenvassdraget,3101,Halden,...,NaN,NaN,NaN,NaN,79.5405,79.6792,79.8333,80.0008,80.2505,"[{'parameterName': 'Vannstand', 'parameter': 1..."
1,1.200.0,Lierelv,59.92038,11.53180,306146,6647624,134,Haldenvassdraget,3226,Aurskog-Høland,...,32.6537,34.9251,36.4982,37.9152,2.2229,2.3076,2.3381,2.3585,2.3764,"[{'parameterName': 'Vannstand', 'parameter': 1..."
2,1.41.0,Lognselva,59.80011,11.44331,300484,6634505,148,Haldenvassdraget,3226,Aurskog-Høland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
3,1.42.0,Øymarksjø,59.33290,11.63712,308715,6581952,109,Haldenvassdraget,3124,Aremark,...,NaN,NaN,NaN,NaN,108.7322,108.9479,109.1339,109.3167,109.5600,"[{'parameterName': 'Vannstand', 'parameter': 1..."
4,1.43.0,Aspern og Ara,59.14667,11.69273,310848,6561073,106,Haldenvassdraget,3124,Aremark,...,NaN,NaN,NaN,NaN,106.0580,106.1420,106.2917,106.4808,106.8153,"[{'parameterName': 'Vannstand', 'parameter': 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1874,99.5.0,Heimste Vikvatn,62.12556,7.52601,110769,6910655,1319,Rødøla,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
1875,99.6.0,Fetvatn,62.13471,7.45939,107429,6912072,1052,Fetvasselva,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
1876,99.7.0,Heimste Veltdalsvatn,62.15934,7.71728,121122,6913264,1174,Rødalselva,3433,Skjåk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
1877,99.8.0,Viavatn,62.10119,7.39499,103649,6908749,1001,Tafjordvassdraget,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
1878,99.9.0,Slettdalsvatn,62.12843,7.38108,103284,6911854,906,Tafjordvassdraget,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."

In [8]:
r.json()['data'][0]

{'stationId': '1.15.0',
 'stationName': 'Femsjø',
 'latitude': 59.13015,
 'longitude': 11.48516,
 'utmEast_Z33': 298887,
 'utmNorth_Z33': 6559841,
 'masl': 81,
 'riverName': 'Haldenvassdraget',
 'councilNumber': '3101',
 'councilName': 'Halden',
 'countyName': 'Østfold',
 'drainageBasinKey': 7,
 'hierarchy': 'Haldenvassdraget',
 'lakeArea': 10.73,
 'lakeName': 'Femsjøen',
 'lakeNo': 316,
 'regineNo': '001.B10',
 'reservoirNo': '78',
 'reservoirName': 'FEMSJØEN',
 'stationTypeName': 'Privat, pålagt',
 'stationStatusName': 'Aktiv',
 'drainageBasinArea': 1514.61,
 'drainageBasinAreaNorway': 1495.678,
 'gradient1085': 0.24,
 'gradientBasin': None,
 'gradientRiver': 0.92,
 'heightMinimum': 77,
 'heightHypso10': 153,
 'heightHypso20': 167,
 'heightHypso30': 187,
 'heightHypso40': 199,
 'heightHypso50': 214,
 'heightHypso60': 230,
 'heightHypso70': 251,
 'heightHypso80': 276,
 'heightHypso90': 311,
 'heightMaximum': 402,
 'lengthKmBasin': 104.61,
 'lengthKmRiver': 143.09,
 'percentAgricul': 7.13,
 'percentBog': 2.55,
 'percentEffBog': None,
 'percentEffLake': 3.29,
 'percentForest': 47.62,
 'percentGlacier': 0,
 'percentLake': 5.74,
 'percentMountain': 0,
 'percentUrban': 0.28,
 'utmZoneGravi': None,
 'utmEastGravi': None,
 'utmNorthGravi': None,
 'utmZoneInlet': None,
 'utmEastInlet': None,
 'utmNorthInlet': None,
 'utmZoneOutlet': None,
 'utmEastOutlet': None,
 'utmNorthOutlet': None,
 'annualRunoff': 677.66,
 'specificDischarge': 14.18,
 'regulationArea': 1512.44,
 'areaReservoirs': 98.51,
 'volumeReservoirs': 119.3,
 'regulationPartReservoirs': 0.18,
 'transferAreaIn': 178.99,
 'transferAreaOut': 0,
 'reservoirAreaIn': 4.64,
 'reservoirAreaOut': 10.83,
 'reservoirVolumeIn': 17.5,
 'reservoirVolumeOut': 11.2,
 'remainingArea': 0,
 'numberReservoirs': 19,
 'firstYearRegulation': 1924,
 'catchmentRegTypeName': 'Regulert m/magasinregulering og overføringer',
 'owner': 'HALDENVASSDRAGETS BRUKSEIERFORENING',
 'qNumberOfYears': 84,
 'qStartYear': 1940,
 'qEndYear': 2024,
 'qm': None,
 'q5': None,
 'q10': None,
 'q20': None,
 'q50': None,
 'hm': 79.5405,
 'h5': 79.6792,
 'h10': 79.8333,
 'h20': 80.0008,
 'h50': 80.2505,
 'culQm': None,
 'culQ5': None,
 'culQ10': None,
 'culQ20': None,
 'culQ50': None,
 'culHm': 79.5405,
 'culH5': 79.6792,
 'culH10': 79.8333,
 'culH20': 80.0008,
 'culH50': 80.2505,
 'seriesList': [{'parameterName': 'Vannstand',
   'parameter': 1000,
   'versionNo': 2,
   'unit': 'm',
   'serieFrom': '1939-07-01T00:00:00',
   'serieTo': None,
   'resolutionList': [{'resTime': 0,
     'method': 'Instantaneous',
     'timeOffset': 0,
     'dataFromTime': '1939-07-01T11:00:00Z',
     'dataToTime': '2026-03-20T12:00:00Z'},
    {'resTime': 60,
     'method': 'Mean',
     'timeOffset': 0,
     'dataFromTime': '2020-12-13T12:00:00Z',
     'dataToTime': '2026-03-20T12:00:00Z'},
    {'resTime': 1440,
     'method': 'Mean',
     'timeOffset': 0,
     'dataFromTime': '1939-07-01T11:00:00Z',
     'dataToTime': '2026-03-19T11:00:00Z'}]},
  {'parameterName': 'Magasinvolum',
   'parameter': 1004,
   'versionNo': 2,
   'unit': 'millioner m³',
   'serieFrom': None,
   'serieTo': None,
   'resolutionList': [{'resTime': 0,
     'method': 'Instantaneous',
     'timeOffset': 0,
     'dataFromTime': '1939-07-01T11:00:00Z',
     'dataToTime': '2026-03-20T12:00:00Z'},
    {'resTime': 60,
     'method': 'Mean',
     'timeOffset': 0,
     'dataFromTime': '2020-12-13T12:00:00Z',
     'dataToTime': '2026-03-20T12:00:00Z'},
    {'resTime': 1440,
     'method': 'Mean',
     'timeOffset': 0,
     'dataFromTime': '1939-07-01T11:00:00Z',
     'dataToTime': '2026-03-19T11:00:00Z'}]}]}

In [ ]:
start, end = '2025-01-01 00:00:00', '2025-01-30 23:00:00'
start_time = datetime.strptime(start, '%Y-%m-%d %H:%M:%S')
end_time = datetime.strptime(end, '%Y-%m-%d %H:%M:%S')

In [10]:
start_time, end_time

(datetime.datetime(2025, 1, 1, 0, 0), datetime.datetime(2025, 1, 30, 23, 0))

In [ ]:
time = pd.date_range("2025-01-01", "2025-12-31 23:00", freq="H")
df = pd.DataFrame({
    "datetime": time,
    "precip_mm": np.round(np.random.gamma(1.5, 1.0, len(time)), 3),
    "temp_C": np.round(5 + 10*np.sin(2*np.pi*(time.dayofyear/365)), 3),
    "shortwave_Wm2": np.round(np.clip(500*np.sin(2*np.pi*(time.hour/24)), 0, None), 3),
    "longwave_Wm2": np.round(np.random.uniform(300, 420, len(time)), 3),
    "wind_mps": np.round(np.random.uniform(4, 10, len(time)), 3),
    "relhum_pct": np.round(np.random.uniform(70, 95, len(time)), 3),
    "pressure": np.round(np.random.uniform(980, 1020, len(time)), 3)
})
df

,datetime,precip_mm,temp_C,shortwave_Wm2,longwave_Wm2,wind_mps,relhum_pct,pressure
0,2025-01-01 00:00:00,2.447,5.172,0.000,320.125,7.620,86.733,1009.946
1,2025-01-01 01:00:00,2.383,5.172,129.410,384.656,7.993,74.095,987.605
2,2025-01-01 02:00:00,3.192,5.172,250.000,384.239,8.049,70.175,997.114
3,2025-01-01 03:00:00,0.759,5.172,353.553,364.490,7.289,87.534,988.409
4,2025-01-01 04:00:00,1.788,5.172,433.013,322.710,8.959,91.852,1013.289
...,...,...,...,...,...,...,...,...
8755,2025-12-31 19:00:00,1.529,5.000,0.000,343.680,5.803,71.896,990.648
8756,2025-12-31 20:00:00,0.724,5.000,0.000,301.795,9.012,93.424,1017.078
8757,2025-12-31 21:00:00,0.415,5.000,0.000,378.202,9.810,85.269,1017.871
8758,2025-12-31 22:00:00,1.135,5.000,0.000,360.407,9.215,84.581,1012.472
8759,2025-12-31 23:00:00,1.438,5.000,0.000,300.634,7.237,72.802,987.983

In [8]:
df.to_csv("alesund_weather.csv", index=False)