In [1]:
import sys, os, json, math, re, shapely, pickle, dotenv, base64, requests, rasterio, sknw
sys.path.append('backend/app/')
import xarray as xr, numpy as np, geopandas as gpd
import pandas as pd, dask.array as da
from Functions import functions, gridFunctions, flowFunctions
import matplotlib.pyplot as plt
from datetime import datetime
from rasterio.features import shapes
from shapely.geometry import shape, LineString, Point
from skimage.morphology import skeletonize
from requests.auth import HTTPBasicAuth

In [2]:
dotenv.load_dotenv()
MET_url = os.getenv('MET_ProstAPI_URL')
MET_client_id = os.getenv('MET_ProstAPI_CLIENT_ID')

In [93]:
url = "https://frost.met.no/observations/v0.jsonld"
headers = {'Accept': 'application/json'}
columns = [
    "mean(air_temperature PT1H)",
    "mean(wind_speed PT1H)", 
    "mean(surface_air_pressure PT1H)",
    "mean(relative_humidity PT1H)",
    "sum(precipitation_amount PT1H)", 
    "mean(surface_downwelling_shortwave_flux_in_air PT1H)",
    'mean(surface_downwelling_longwave_flux_in_air PT1H)'
]
params = {
    "sources": "SN18700", "elements": ",".join(columns),
    "referencetime": "2024-01-01T00:00:00Z/2024-01-02T00:00:00Z"
}
r = requests.get(
    url, headers=headers, 
    params=params,
    auth=HTTPBasicAuth(MET_client_id, "")
)
data, rows = r.json()["data"], []
for item in data:
    time = item['referenceTime']
    for obs in item['observations']:
        rows.append({
            "timestamp": time, 'element': obs['elementId'],
            "value": obs['value'], 'timeResolution': obs['timeResolution'],
            "height": obs.get('level', {}).get('value'), "qualityCode": obs.get('qualityCode')
        })
df = pd.DataFrame(rows)
df['timestamp'] = pd.to_datetime(df['timestamp']).dt.strftime('%Y-%m-%d %H:%M:%S')
df = df[df['timeResolution'] == 'PT1H'].reset_index(drop=True)
weather_df = pd.DataFrame(data={'timestamp': df['timestamp'].unique()})

In [94]:
pre_mask = (df['element'] == 'sum(precipitation_amount PT1H)')
df.loc[pre_mask, 'precipitation'] = df.loc[pre_mask, 'value']
pre_df = df[~df['precipitation'].isna()]
weather_df = weather_df.merge(pre_df[['timestamp', 'precipitation']], how='left', on='timestamp')
temp_mask = (df['element'] == 'mean(air_temperature PT1H)') & (df['height'] == 2)
df.loc[temp_mask, 'temperature'] = df.loc[temp_mask, 'value']
temp_df = df[~df['temperature'].isna()]
weather_df = weather_df.merge(temp_df[['timestamp', 'temperature']], how='left', on='timestamp')
short_mask = (df['element'] == 'mean(surface_downwelling_shortwave_flux_in_air PT1H)')
df.loc[short_mask, 'short_wave_radiation'] = df.loc[short_mask, 'value']
short_df = df[~df['short_wave_radiation'].isna()]
weather_df = weather_df.merge(short_df[['timestamp', 'short_wave_radiation']], how='left', on='timestamp')
long_mask = (df['element'] == 'mean(surface_downwelling_longwave_flux_in_air PT1H)')
df.loc[long_mask, 'long_wave_radiation'] = df.loc[long_mask, 'value']
long_df = df[~df['long_wave_radiation'].isna()]
weather_df = weather_df.merge(long_df[['timestamp', 'long_wave_radiation']], how='left', on='timestamp')
wind_mask = (df['element'] == 'mean(wind_speed PT1H)') & (df['height'] == 10)
df.loc[wind_mask, 'wind_speed'] = df.loc[wind_mask, 'value']
wind_df = df[~df['wind_speed'].isna()]
weather_df = weather_df.merge(wind_df[['timestamp', 'wind_speed']], how='left', on='timestamp')
humidity_mask = (df['element'] == 'mean(relative_humidity PT1H)')
df.loc[humidity_mask, 'humidity'] = df.loc[humidity_mask, 'value']
humidity_df = df[~df['humidity'].isna()]
weather_df = weather_df.merge(humidity_df[['timestamp', 'humidity']], how='left', on='timestamp')
pressure_mask = (df['element'] == 'mean(surface_air_pressure PT1H)')
df.loc[pressure_mask, 'pressure'] = df.loc[pressure_mask, 'value']
pressure_df = df[~df['pressure'].isna()]
weather_df = weather_df.merge(pressure_df[['timestamp', 'pressure']], how='left', on='timestamp')
weather_df

,timestamp,precipitation,temperature,short_wave_radiation,long_wave_radiation,wind_speed,humidity,pressure
0,2024-01-01 00:00:00,0.3,NaN,-0.80,NaN,NaN,NaN,NaN
1,2024-01-01 01:00:00,0.4,NaN,-0.85,NaN,NaN,NaN,NaN
2,2024-01-01 02:00:00,0.4,NaN,-0.87,NaN,NaN,NaN,NaN
3,2024-01-01 03:00:00,0.4,NaN,-0.94,NaN,NaN,NaN,NaN
4,2024-01-01 04:00:00,0.4,NaN,-0.93,NaN,NaN,NaN,NaN
5,2024-01-01 05:00:00,0.5,NaN,-0.97,NaN,NaN,NaN,NaN
6,2024-01-01 06:00:00,0.6,NaN,-0.84,NaN,NaN,NaN,NaN
7,2024-01-01 07:00:00,0.3,NaN,-0.76,NaN,NaN,NaN,NaN
8,2024-01-01 08:00:00,0.8,NaN,-0.76,NaN,NaN,NaN,NaN
9,2024-01-01 09:00:00,0.5,NaN,2.38,NaN,NaN,NaN,NaN
10,2024-01-01 10:00:00,0.4,NaN,17.32,NaN,NaN,NaN,NaN
11,2024-01-01 11:00:00,0.5,NaN,20.00,NaN,NaN,NaN,NaN
12,2024-01-01 12:00:00,0.5,NaN,12.21,NaN,NaN,NaN,NaN
13,2024-01-01 13:00:00,0.4,NaN,11.77,NaN,NaN,NaN,NaN
14,2024-01-01 14:00:00,0.1,NaN,9.66,NaN,NaN,NaN,NaN
15,2024-01-01 15:00:00,0.3,NaN,0.69,NaN,NaN,NaN,NaN
16,2024-01-01 16:00:00,0.3,NaN,-0.83,NaN,NaN,NaN,NaN
17,2024-01-01 17:00:00,0.3,NaN,-0.81,NaN,NaN,NaN,NaN
18,2024-01-01 18:00:00,0.3,NaN,-0.79,NaN,NaN,NaN,NaN
19,2024-01-01 19:00:00,0.4,NaN,-0.75,NaN,NaN,NaN,NaN
20,2024-01-01 20:00:00,0.4,NaN,-0.75,NaN,NaN,NaN,NaN
21,2024-01-01 21:00:00,0.4,NaN,-0.74,NaN,NaN,NaN,NaN
22,2024-01-01 22:00:00,0.1,NaN,-0.81,NaN,NaN,NaN,NaN
23,2024-01-01 23:00:00,0.1,NaN,-0.81,NaN,NaN,NaN,NaN

In [96]:
np.array(weather_df).tolist()

[['2024-01-01 00:00:00', 0.3, nan, -0.8, nan, nan, nan, nan],
 ['2024-01-01 01:00:00', 0.4, nan, -0.85, nan, nan, nan, nan],
 ['2024-01-01 02:00:00', 0.4, nan, -0.87, nan, nan, nan, nan],
 ['2024-01-01 03:00:00', 0.4, nan, -0.94, nan, nan, nan, nan],
 ['2024-01-01 04:00:00', 0.4, nan, -0.93, nan, nan, nan, nan],
 ['2024-01-01 05:00:00', 0.5, nan, -0.97, nan, nan, nan, nan],
 ['2024-01-01 06:00:00', 0.6, nan, -0.84, nan, nan, nan, nan],
 ['2024-01-01 07:00:00', 0.3, nan, -0.76, nan, nan, nan, nan],
 ['2024-01-01 08:00:00', 0.8, nan, -0.76, nan, nan, nan, nan],
 ['2024-01-01 09:00:00', 0.5, nan, 2.38, nan, nan, nan, nan],
 ['2024-01-01 10:00:00', 0.4, nan, 17.32, nan, nan, nan, nan],
 ['2024-01-01 11:00:00', 0.5, nan, 20.0, nan, nan, nan, nan],
 ['2024-01-01 12:00:00', 0.5, nan, 12.21, nan, nan, nan, nan],
 ['2024-01-01 13:00:00', 0.4, nan, 11.77, nan, nan, nan, nan],
 ['2024-01-01 14:00:00', 0.1, nan, 9.66, nan, nan, nan, nan],
 ['2024-01-01 15:00:00', 0.3, nan, 0.69, nan, nan, nan, nan],
 ['2024-01-01 16:00:00', 0.3, nan, -0.83, nan, nan, nan, nan],
 ['2024-01-01 17:00:00', 0.3, nan, -0.81, nan, nan, nan, nan],
 ['2024-01-01 18:00:00', 0.3, nan, -0.79, nan, nan, nan, nan],
 ['2024-01-01 19:00:00', 0.4, nan, -0.75, nan, nan, nan, nan],
 ['2024-01-01 20:00:00', 0.4, nan, -0.75, nan, nan, nan, nan],
 ['2024-01-01 21:00:00', 0.4, nan, -0.74, nan, nan, nan, nan],
 ['2024-01-01 22:00:00', 0.1, nan, -0.81, nan, nan, nan, nan],
 ['2024-01-01 23:00:00', 0.1, nan, -0.81, nan, nan, nan, nan]]

In [ ]:
df['id'].to_list()

['accumulated(liquid_water_content_of_surface_snow)',
 'accumulated(precipitation_amount)',
 'air_pressure',
 'air_pressure_at_sea_level',
 'air_pressure_at_sea_level_qnh',
 'air_temperature',
 'air_temperature_vertical_difference',
 'altitude',
 'automatic_metar',
 'barometer_temperature',
 'battery_voltage',
 'beaufort_wind_force',
 'best_estimate_max(air_temperature P1D)',
 'best_estimate_mean(air_temperature P1D)',
 'best_estimate_mean(air_temperature P1M)',
 'best_estimate_mean(air_temperature P1Y)',
 'best_estimate_mean(air_temperature P3M)',
 'best_estimate_mean(air_temperature P6M)',
 'best_estimate_mean(air_temperature_anomaly P1M 1961_1990)',
 'best_estimate_mean(air_temperature_anomaly P1M 1991_2020)',
 'best_estimate_mean(air_temperature_anomaly P1Y 1961_1990)',
 'best_estimate_mean(air_temperature_anomaly P1Y 1991_2020)',
 'best_estimate_mean(air_temperature_anomaly P3M 1961_1990)',
 'best_estimate_mean(air_temperature_anomaly P3M 1991_2020)',
 'best_estimate_mean(air_temperature_anomaly P6M 1961_1990)',
 'best_estimate_mean(air_temperature_anomaly P6M 1991_2020)',
 'best_estimate_min(air_temperature P1D)',
 'best_estimate_sum(precipitation_amount P1D)',
 'best_estimate_sum(precipitation_amount P1M)',
 'best_estimate_sum(precipitation_amount P1Y)',
 'best_estimate_sum(precipitation_amount P3M)',
 'best_estimate_sum(precipitation_amount P6M)',
 'best_estimate_sum(precipitation_amount_anomaly P1M 1961_1990)',
 'best_estimate_sum(precipitation_amount_anomaly P1M 1991_2020)',
 'best_estimate_sum(precipitation_amount_anomaly P1Y 1961_1990)',
 'best_estimate_sum(precipitation_amount_anomaly P1Y 1991_2020)',
 'best_estimate_sum(precipitation_amount_anomaly P3M 1961_1990)',
 'best_estimate_sum(precipitation_amount_anomaly P3M 1991_2020)',
 'best_estimate_sum(precipitation_amount_anomaly P6M 1961_1990)',
 'best_estimate_sum(precipitation_amount_anomaly P6M 1991_2020)',
 'boolean_clear_sky_weather(cloud_area_fraction P1D)',
 'boolean_fair_weather(cloud_area_fraction P1D)',
 'boolean_overcast_weather(cloud_area_fraction P1D)',
 'ceiling_and_visibility_ok',
 'cloud_area_fraction',
 'cloud_area_fraction1',
 'cloud_area_fraction2',
 'cloud_area_fraction3',
 'cloud_area_fraction4',
 'cloud_base_height',
 'cloud_base_height1',
 'cloud_base_height2',
 'cloud_base_height3',
 'cloud_base_height4',
 'cloud_top_height1',
 'cloud_top_height2',
 'cloud_top_height3',
 'cloud_top_height4',
 'cloud_type1',
 'cloud_type2',
 'cloud_type3',
 'cloud_type4',
 'cloud_type_icao1',
 'cloud_type_icao2',
 'cloud_type_icao3',
 'cloud_type_icao4',
 'day_of_year_for_birch_leafing',
 'depth',
 'dew_point_height_estimated',
 'dew_point_temperature',
 'direction_of_sea_ice_edge',
 'direction_of_visibility_in_air_operationally_significant',
 'direction_of_visibility_in_air_predominant',
 'flourescence_of_chlorophyl_a_in_sea_water',
 'flourescense_of_dissolved_organic_carbon_in_sea_water',
 'flow_rate',
 'fractional_saturation_of_oxygen_in_sea_water',
 'fresh_water_temperature',
 'grass_temperature',
 'high_type_cloud',
 'ice_of_land_origin_type',
 'icing_rate_type_on_ship',
 'icing_thickness',
 'icing_type_on_ship',
 'indicator_station_type_weather',
 'instrument_laser_signal_backscatter_intensity',
 'instrument_temperature_longwave_radiation',
 'instrument_temperature_lower_inlet_geonor',
 'instrument_temperature_shortwave_radiation',
 'instrument_temperature_upper_inlet_geonor',
 'integral_of_deficit(mean(air_temperature P1D) P1D 17.0)',
 'integral_of_deficit(mean(air_temperature P1D) P1M 17.0)',
 'integral_of_deficit(mean(air_temperature P1D) P1Y 17.0)',
 'integral_of_deficit(mean(air_temperature P1D) P3M 17.0)',
 'integral_of_deficit(mean(air_temperature P1D) P6M 17.0)',
 'integral_of_deficit_interpolated(mean(air_temperature P1D) P1M 17.0)',
 'integral_of_deficit_interpolated(mean(air_temperature P1D) P1Y 17.0)',
 'integral_of_deficit_interpolated(mean(air_temperature_normal P1D 1961_1990) P1M 17.0)',
 'integral_of_deficit_interpolated(mean(air_temperature_normal P1D 1961_1990) P1Y 17.0)',
 'integral_of_deficit_interpolated(mean(air_temperature_normal P1D 1991_2020) P1M 17.0)',
 'integral_of_deficit_interpolated(mean(air_temperature_normal P1D 1991_2020) P1Y 17.0)',
 'integral_of_excess(mean(air_temperature P1D) P1D 0.0)',
 'integral_of_excess(mean(air_temperature P1D) P1D 5.0)',
 'integral_of_excess(mean(air_temperature P1D) P1M 0.0)',
 'integral_of_excess(mean(air_temperature P1D) P1M 5.0)',
 'integral_of_excess(mean(air_temperature P1D) P3M 0.0)',
 'integral_of_excess(mean(air_temperature P1D) P3M 5.0)',
 'latitude',
 'liquid_water_content_of_surface_snow',
 'longitude',
 'low_type_cloud',
 'low_type_cloud_area_fraction',
 'mass_concentration_of_blue_green_algae_in_sea_water',
 'mass_concentration_of_chlorophyll_in_sea_water',
 'mass_concentration_of_cryptophytes_in_sea_water',
 'mass_concentration_of_diatoms_in_sea_water',
 'mass_concentration_of_green_algae_in_sea_water',
 'max(accumulated(precipitation_amount) PT1H)',
 'max(air_gap PT10M)',
 'max(air_pressure_at_sea_level P1D)',
 'max(air_pressure_at_sea_level P1M)',
 'max(air_pressure_at_sea_level P3M)',
 'max(air_temperature P1D)',
 'max(air_temperature P1M)',
 'max(air_temperature P1Y)',
 'max(air_temperature P3M)',
 'max(air_temperature P6M)',
 'max(air_temperature PT10M)',
 'max(air_temperature PT12H)',
 'max(air_temperature PT1H)',
 'max(beaufort_wind_force PT6H)',
 'max(cloud_area_fraction P1D)',
 'max(cloud_area_fraction P1M)',
 'max(cloud_area_fraction P3M)',
 'max(dew_point_temperature PT1H)',
 'max(grass_temperature PT1H)',
 'max(hail_diameter PT1H)',
 'max(hail_diameter PT1M)',
 'max(max(wind_speed P1D) P1M)',
 'max(max(wind_speed P1D) P3M)',
 'max(max(wind_speed PT1H) P1D)',
 'max(mean(surface_downwelling_shortwave_flux_in_air PT1M) PT1H)',
 'max(mean(surface_upwelling_longwave_flux_in_air PT1M) PT1H)',
 'max(min(grass_temperature P1D) P1M)',
 'max(min(grass_temperature P1D) P3M)',
 'max(rainfall_rate PT1M)',
 'max(relative_humidity P1D)',
 'max(relative_humidity P1M)',
 'max(relative_humidity P3M)',
 'max(relative_humidity PT10M)',
 'max(relative_humidity PT1H)',
 'max(road_surface_temperature PT10M)',
 'max(runway_temperature PT1H)',
 'max(sea_state P1D)',
 'max(sea_state P1M)',
 'max(sea_state P3M)',
 'max(sea_surface_height_above_lowest_astronomical_tide PT10M)',
 'max(sea_surface_temperature P1M)',
 'max(sea_surface_temperature P3M)',
 'max(sea_surface_temperature PT1H)',
 'max(sea_surface_wave_mean_period P1D)',
 'max(sea_surface_wave_mean_period P1M)',
 'max(sea_surface_wave_period P1D)',
 'max(sea_surface_wave_period P1M)',
 'max(sea_surface_wave_significant_height P1D)',
 'max(sea_surface_wave_significant_height P1M)',
 'max(snow_coverage_type P1M)',
 'max(snow_coverage_type P3M)',
 'max(snow_temperature PT1H)',
 'max(sum(duration_of_sunshine P1D) P1M)',
 'max(sum(duration_of_sunshine P1D) P3M)',
 'max(sum(precipitation_amount P1D) P1M)',
 'max(surface_air_pressure P1D)',
 'max(surface_air_pressure P1M)',
 'max(surface_air_pressure P3M)',
 'max(surface_air_pressure PT1H)',
 'max(surface_snow_thickness P1M)',
 'max(surface_snow_thickness P3M)',
 'max(surface_snow_thickness PT1H)',
 'max(virtual_temperature PT1H)',
 'max(visibility_in_air_poorest_direction P1D)',
 'max(visibility_in_air_poorest_direction P1M)',
 'max(visibility_in_air_poorest_direction P3M)',
 'max(visibility_in_air_rvr)_validation_x1r',
 'max(visibility_in_air_rvr)_validation_x2r',
 'max(visibility_in_air_rvr)_validation_x3r',
 'max(visibility_in_air_rvr_x1r)',
 'max(visibility_in_air_rvr_x2r)',
 'max(visibility_in_air_rvr_x3r)',
 'max(wind_from_direction_of_gust PT10M)',
 'max(wind_from_direction_of_gust PT2M)',
 'max(wind_speed P1D)',
 'max(wind_speed P1M)',
 'max(wind_speed P3M)',
 'max(wind_speed PT1H)',
 'max(wind_speed PT20M)',
 'max(wind_speed PT3H)',
 'max(wind_speed PT6H)',
 'max(wind_speed)',
 'max(wind_speed_of_gust P1D)',
 'max(wind_speed_of_gust P1M)',
 'max(wind_speed_of_gust P3M)',
 'max(wind_speed_of_gust PT10M)',
 'max(wind_speed_of_gust PT1H)',
 'max(wind_speed_of_gust PT1M)',
 'max(wind_speed_of_gust PT20M)',
 'max(wind_speed_of_gust PT2M)',
 'max(wind_speed_of_gust PT6H)',
 'max_wind_speed(wind_from_direction PT1H)',
 'max_wind_speed(wind_from_direction PT3H)',
 'max_wind_speed(wind_from_direction PT6H)',
 'max_wind_speed(wind_from_direction_of_gust PT10M)',
 'max_wind_speed(wind_from_direction_of_gust PT1H)',
 'mean(air_gap PT10M)',
 'mean(air_pressure_at_sea_level P1D)',
 'mean(air_pressure_at_sea_level P1M)',
 'mean(air_pressure_at_sea_level P1Y)',
 'mean(air_pressure_at_sea_level P3M)',
 'mean(air_pressure_at_sea_level_normal P1M 1961_1990)',
 'mean(air_pressure_at_sea_level_normal P1M 1991_2020)',
 'mean(air_pressure_at_sea_level_normal P1Y 1961_1990)',
 'mean(air_pressure_at_sea_level_normal P1Y 1991_2020)',
 'mean(air_temperature P1D)',
 'mean(air_temperature P1M)',
 'mean(air_temperature P1Y)',
 'mean(air_temperature P3M)',
 'mean(air_temperature P6M)',
 'mean(air_temperature PT1H)',
 'mean(air_temperature_anomaly P1M 1961_1990)',
 'mean(air_temperature_anomaly P1M 1971_2000)',
 'mean(air_temperature_anomaly P1M 1991_2020)',
 'mean(air_temperature_anomaly P1Y 1961_1990)',
 'mean(air_temperature_anomaly P1Y 1991_2020)',
 'mean(air_temperature_anomaly P3M 1961_1990)',
 'mean(air_temperature_anomaly P3M 1991_2020)',
 'mean(air_temperature_anomaly P6M 1961_1990)',
 'mean(air_temperature_anomaly P6M 1991_2020)',
 'mean(air_temperature_normal P1D 1961_1990)',
 'mean(air_temperature_normal P1D 1991_2020)',
 'mean(air_temperature_normal P1M 1961_1990)',
 'mean(air_temperature_normal P1M 1991_2020)',
 'mean(air_temperature_normal P1Y 1961_1990)',
 'mean(air_temperature_normal P1Y 1991_2020)',
 'mean(bulk_soil_electrical_conductivity PT1H)',
 'mean(bulk_soil_relative_permittivity PT1H)',
 'mean(cloud_area_fraction P1D)',
 'mean(cloud_area_fraction P1M)',
 'mean(cloud_area_fraction P1Y)',
 'mean(cloud_area_fraction P3M)',
 'mean(cloud_area_fraction P6M)',
 'mean(dew_point_temperature P1D)',
 'mean(dew_point_temperature P1M)',
 'mean(dew_point_temperature PT1H)',
 'mean(difference_between_downwelling_longwave_flux_and_instrument_longwave_radiation PT10M)',
 'mean(difference_between_downwelling_longwave_flux_and_instrument_longwave_radiation PT1M)',
 'mean(difference_between_upwelling_longwave_flux_and_instrument_longwave_radiation PT10M)',
 'mean(difference_between_upwelling_longwave_flux_and_instrument_longwave_radiation PT1M)',
 'mean(diffuse_downwelling_shortwave_flux_in_air P1D)',
 'mean(diffuse_downwelling_shortwave_flux_in_air PT1H)',
 'mean(diffuse_downwelling_shortwave_flux_in_air PT1M)',
 'mean(grass_temperature PT1H)',
 'mean(humidity_mixing_ratio P1M)',
 'mean(max(air_temperature P1D) P1M)',
 'mean(max(air_temperature P1D) P1Y)',
 'mean(max(air_temperature P1D) P3M)',
 'mean(max(air_temperature_normal P1D 1961_1990) P1M)',
 'mean(max(air_temperature_normal P1D 1961_1990) P1Y)',
 'mean(max(air_temperature_normal P1D 1991_2020) P1M)',
 'mean(max(air_temperature_normal P1D 1991_2020) P1Y)',
 'mean(max(wind_speed P1D) P1M)',
 'mean(max(wind_speed P1D) P3M)',
 'mean(max(wind_speed PT1H) P1D)',
 'mean(min(air_temperature P1D) P1M)',
 'mean(min(air_temperature P1D) P1Y)',
 'mean(min(air_temperature P1D) P3M)',
 'mean(min(air_temperature_normal P1D 1961_1990) P1M)',
 'mean(min(air_temperature_normal P1D 1961_1990) P1Y)',
 'mean(min(air_temperature_normal P1D 1991_2020) P1M)',
 'mean(min(air_temperature_normal P1D 1991_2020) P1Y)',
 'mean(min(grass_temperature P1D) P1M)',
 'mean(min(grass_temperature P1D) P3M)',
 'mean(rainfall_rate PT1M)',
 'mean(relative_humidity P1D)',
 'mean(relative_humidity P1M)',
 'mean(relative_humidity P3M)',
 'mean(relative_humidity PT1H)',
 'mean(relative_humidity_normal P1M 1961_1990)',
 'mean(relative_humidity_normal P1M 1991_2020)',
 'mean(road_freezing_point_temperature PT1M)',
 'mean(road_surface_temperature PT1M)',
 'mean(runway_temperature PT1H)',
 'mean(sea_surface_height_above_lowest_astronomical_tide PT10M)',
 'mean(sea_surface_temperature P1D)',
 'mean(sea_surface_temperature P1M)',
 'mean(sea_surface_temperature P3M)',
 'mean(sea_surface_temperature PT1H)',
 'mean(sea_surface_wave_directional_spread)',
 'mean(sea_surface_wave_mean_period P1D)',
 'mean(sea_surface_wave_mean_period P1M)',
 'mean(sea_surface_wave_period P1D)',
 'mean(sea_surface_wave_period P1M)',
 'mean(sea_surface_wave_significant_height P1D)',
 'mean(sea_surface_wave_significant_height P1M)',
 'mean(snow_coverage_type P1M)',
 'mean(snow_coverage_type P3M)',
 'mean(snow_temperature PT1H)',
 'mean(soil_temperature P1D)',
 'mean(soil_temperature PT1H)',
 'mean(solar_irradiance PT1H)',
 'mean(solar_irradiance PT1M)',
 'mean(specific_humidity P1M)',
 'mean(stream_stage PT1M)',
 'mean(surface_air_pressure P1D)',
 'mean(surface_air_pressure P1M)',
 'mean(surface_air_pressure P1Y)',
 'mean(surface_air_pressure P3M)',
 'mean(surface_air_pressure PT1H)',
 'mean(surface_air_pressure_normal P1M 1961_1990)',
 'mean(surface_air_pressure_normal P1M 1991_2020)',
 'mean(surface_air_pressure_normal P1Y 1961_1990)',
 'mean(surface_air_pressure_normal P1Y 1991_2020)',
 'mean(surface_albedo PT1H)',
 'mean(surface_downwelling_longwave_flux_in_air PT1H)',
 'mean(surface_downwelling_longwave_flux_in_air PT1M)',
 'mean(surface_downwelling_photosynthetic_radiative_flux_in_air PT1H)',
 'mean(surface_downwelling_shortwave_flux_in_air P1D)',
 'mean(surface_downwelling_shortwave_flux_in_air PT10M)',
 'mean(surface_downwelling_shortwave_flux_in_air PT1H)',
 'mean(surface_downwelling_shortwave_flux_in_air PT1M)',
 'mean(surface_net_downward_radiative_flux PT1H)',
 'mean(surface_net_downward_radiative_flux PT1M)',
 'mean(surface_snow_thickness P1M)',
 'mean(surface_snow_thickness P3M)',
 'mean(surface_snow_thickness PT1H)',
 'mean(surface_upwelling_longwave_flux_in_air PT1H)',
 'mean(surface_upwelling_longwave_flux_in_air PT1M)',
 'mean(surface_upwelling_shortwave_flux_in_air P1D)',
 'mean(surface_upwelling_shortwave_flux_in_air PT1H)',
 'mean(surface_upwelling_shortwave_flux_in_air PT1M)',
 'mean(vessel_direction PT3H)',
 'mean(vessel_speed PT3H)',
 'mean(virtual_temperature PT1M)',
 'mean(water_vapor_partial_pressure_in_air P1D)',
 'mean(water_vapor_partial_pressure_in_air P1M)',
 'mean(water_vapor_partial_pressure_in_air P3M)',
 'mean(wind_from_direction PT1H)',
 'mean(wind_from_direction PT1M)',
 'mean(wind_from_direction PT2M)',
 'mean(wind_speed P1D)',
 'mean(wind_speed P1M)',
 'mean(wind_speed P3M)',
 'mean(wind_speed PT1H)',
 'mean(wind_speed PT1M)',
 'mean(wind_speed PT2M)',
 'mean(wind_speed_of_gust P1D)',
 'mean(wind_speed_of_gust P1M)',
 'mean(wind_speed_of_gust P3M)',
 'mean_k(air_temperature P1D)',
 'mean_k(air_temperature P1M)',
 'medium_type_cloud',
 'min(accumulated(precipitation_amount) PT1H)',
 'min(air_gap PT10M)',
 'min(air_pressure_at_sea_level P1D)',
 'min(air_pressure_at_sea_level P1M)',
 'min(air_pressure_at_sea_level P3M)',
 'min(air_temperature P1D)',
 'min(air_temperature P1M)',
 'min(air_temperature P1Y)',
 'min(air_temperature P3M)',
 'min(air_temperature P6M)',
 'min(air_temperature PT10M)',
 'min(air_temperature PT12H)',
 'min(air_temperature PT1H)',
 'min(cloud_area_fraction P1D)',
 'min(cloud_area_fraction P1M)',
 'min(cloud_area_fraction P3M)',
 'min(cloud_base_height PT1H)',
 'min(dew_point_temperature PT1H)',
 'min(grass_temperature P1D)',
 'min(grass_temperature PT12H)',
 'min(grass_temperature PT1H)',
 'min(max(wind_speed P1D) P1M)',
 'min(max(wind_speed P1D) P3M)',
 'min(max(wind_speed PT1H) P1D)',
 'min(min(grass_temperature P1D) P1M)',
 'min(min(grass_temperature P1D) P3M)',
 'min(relative_humidity P1D)',
 'min(relative_humidity P1M)',
 'min(relative_humidity P3M)',
 'min(relative_humidity PT10M)',
 'min(relative_humidity PT1H)',
 'min(road_surface_temperature PT10M)',
 'min(runway_temperature PT1H)',
 'min(sea_state P1D)',
 'min(sea_state P1M)',
 'min(sea_state P3M)',
 'min(sea_surface_height_above_lowest_astronomical_tide PT10M)',
 'min(sea_surface_temperature P1M)',
 'min(sea_surface_temperature P3M)',
 'min(sea_surface_temperature PT1H)',
 'min(sea_surface_wave_mean_period P1D)',
 'min(sea_surface_wave_mean_period P1M)',
 'min(sea_surface_wave_period P1D)',
 'min(sea_surface_wave_period P1M)',
 'min(sea_surface_wave_significant_height P1D)',
 'min(sea_surface_wave_significant_height P1M)',
 'min(snow_coverage_type P1M)',
 'min(snow_coverage_type P3M)',
 'min(snow_temperature PT1H)',
 'min(sum(duration_of_sunshine P1D) P1M)',
 'min(sum(duration_of_sunshine P1D) P3M)',
 'min(surface_air_pressure P1D)',
 'min(surface_air_pressure P1M)',
 'min(surface_air_pressure P3M)',
 'min(surface_air_pressure PT1H)',
 'min(surface_snow_thickness P1M)',
 'min(surface_snow_thickness P3M)',
 'min(surface_snow_thickness PT1H)',
 'min(virtual_temperature PT1H)',
 'min(visibility_in_air_poorest_direction P1D)',
 'min(visibility_in_air_poorest_direction P1M)',
 'min(visibility_in_air_poorest_direction P3M)',
 'min(wind_from_direction_of_gust PT10M)',
 'min(wind_from_direction_of_gust PT2M)',
 'min(wind_speed P1D)',
 'min(wind_speed P1M)',
 'min(wind_speed P3M)',
 'min(wind_speed PT1H)',
 'min(wind_speed_of_gust P1D)',
 'min(wind_speed_of_gust P1M)',
 'min(wind_speed_of_gust P3M)',
 'min(wind_speed_of_gust PT10M)',
 'min(wind_speed_of_gust PT2M)',
 'mole_concentration_of_dissolved_molecular_oxygen_in_sea_water',
 'number_of_days_gte(sum(precipitation_amount P1D) P1M 1.0)',
 'number_of_days_gte(sum(precipitation_amount_normal P1D 1961_1990) P1M 1.0)',
 'number_of_days_gte(sum(precipitation_amount_normal P1D 1961_1990) P1Y 1.0)',
 'number_of_days_gte(sum(precipitation_amount_normal P1D 1991_2020) P1M 1.0)',
 'number_of_days_gte(sum(precipitation_amount_normal P1D 1991_2020) P1Y 1.0)',
 'over_time(change_in_surface_snow_thickness P1D)',
 'over_time(equivalent_reflectivity_factor PT1M)',
 'over_time(gauge_content_difference PT1H)',
 'over_time(humidity_mixing_ratio P1D)',
 'over_time(number_of_particles PT1H)',
 'over_time(number_of_particles PT1M)',
 'over_time(precipitation_class1 P1D)',
 'over_time(precipitation_type P1D)',
 'over_time(precipitation_type_automatic P1D)',
 'over_time(precipitation_type_road PT10M)',
 'over_time(precipitation_type_visual P1D)',
 'over_time(sum(time_of_maximum_precipitation_amount P1D) P1M)',
 'over_time(tendency_of_surface_air_pressure PT3H)',
 'over_time(thickness_of_snowfall_amount P1D)',
 'over_time(time_of_maximum_air_temperature P1M)',
 'over_time(time_of_maximum_wind_speed P1M)',
 'over_time(time_of_maximum_wind_speed PT1H)',
 'over_time(time_of_maximum_wind_speed_of_gust PT1H)',
 'over_time(time_of_minimum_air_temperature P1M)',
 'over_time(weather_class1_primary_significance P1D)',
 'over_time(weather_class1_primary_significance PT6H)',
 'over_time(weather_class1_primary_significance_intensity PT6H)',
 'over_time(weather_class1_quaternary_significance PT6H)',
 'over_time(weather_class1_secondary_significance PT6H)',
 'over_time(weather_class1_secondary_significance_intensity PT6H)',
 'over_time(weather_class1_tertiary_significance PT6H)',
 'over_time(weather_class1_tertiary_significance_intensity PT6H)',
 'over_time(weather_cloud_symbol PT6H)',
 'over_time(weather_type_additional1)',
 'over_time(weather_type_additional2)',
 'over_time(weather_type_additional3)',
 'over_time(weather_type_automatic PT1M)',
 'over_time(weather_type_automatic_primary_significance)',
 'over_time(weather_type_automatic_secondary_significance)',
 'over_time(weather_type_primary_significance)',
 'over_time(weather_type_primary_significance_metar)',
 'over_time(weather_type_secondary_significance)',
 'over_time(weather_type_secondary_significance_metar)',
 'over_time(weather_type_tertiary_significance_metar)',
 'precipitation_amount',
 'precipitation_duration_period',
 'precipitation_group_indicator',
 'region_mean(air_temperature P1M 1961_1990)',
 'region_mean(air_temperature P1M 1991_2020)',
 'region_mean(air_temperature P1Y 1961_1990)',

In [3]:
url, client_id

('https://frost.met.no', 'f6d537e9-cf9d-4a87-a838-02d607fe68bd')

In [ ]:
start, end = '2025-01-01 00:00:00', '2025-01-30 23:00:00'
start_time = datetime.strptime(start, '%Y-%m-%d %H:%M:%S')
end_time = datetime.strptime(end, '%Y-%m-%d %H:%M:%S')

In [10]:
start_time, end_time

(datetime.datetime(2025, 1, 1, 0, 0), datetime.datetime(2025, 1, 30, 23, 0))

In [ ]:
time = pd.date_range("2025-01-01", "2025-12-31 23:00", freq="H")
df = pd.DataFrame({
    "datetime": time,
    "precip_mm": np.round(np.random.gamma(1.5, 1.0, len(time)), 3),
    "temp_C": np.round(5 + 10*np.sin(2*np.pi*(time.dayofyear/365)), 3),
    "shortwave_Wm2": np.round(np.clip(500*np.sin(2*np.pi*(time.hour/24)), 0, None), 3),
    "longwave_Wm2": np.round(np.random.uniform(300, 420, len(time)), 3),
    "wind_mps": np.round(np.random.uniform(4, 10, len(time)), 3),
    "relhum_pct": np.round(np.random.uniform(70, 95, len(time)), 3),
    "pressure": np.round(np.random.uniform(980, 1020, len(time)), 3)
})
df

,datetime,precip_mm,temp_C,shortwave_Wm2,longwave_Wm2,wind_mps,relhum_pct,pressure
0,2025-01-01 00:00:00,2.447,5.172,0.000,320.125,7.620,86.733,1009.946
1,2025-01-01 01:00:00,2.383,5.172,129.410,384.656,7.993,74.095,987.605
2,2025-01-01 02:00:00,3.192,5.172,250.000,384.239,8.049,70.175,997.114
3,2025-01-01 03:00:00,0.759,5.172,353.553,364.490,7.289,87.534,988.409
4,2025-01-01 04:00:00,1.788,5.172,433.013,322.710,8.959,91.852,1013.289
...,...,...,...,...,...,...,...,...
8755,2025-12-31 19:00:00,1.529,5.000,0.000,343.680,5.803,71.896,990.648
8756,2025-12-31 20:00:00,0.724,5.000,0.000,301.795,9.012,93.424,1017.078
8757,2025-12-31 21:00:00,0.415,5.000,0.000,378.202,9.810,85.269,1017.871
8758,2025-12-31 22:00:00,1.135,5.000,0.000,360.407,9.215,84.581,1012.472
8759,2025-12-31 23:00:00,1.438,5.000,0.000,300.634,7.237,72.802,987.983

In [8]:
df.to_csv("alesund_weather.csv", index=False)