In [1]:
import sys, os, json, math, re, shapely, pickle, dotenv, base64, requests, rasterio, sknw
sys.path.append('backend/app/')
import xarray as xr, numpy as np, geopandas as gpd
import pandas as pd, dask.array as da
from Functions import functions, gridFunctions, flowFunctions
import matplotlib.pyplot as plt
from datetime import datetime
from rasterio.features import shapes
from shapely.geometry import shape, LineString, Point
from skimage.morphology import skeletonize
from requests.auth import HTTPBasicAuth

In [2]:
dotenv.load_dotenv()
url = os.getenv('NVE_URL')
client_id = os.getenv('NVE_API_KEY')
headers = {'Accept': 'application/json', "X-API-Key": client_id}

In [9]:
new_url = f'{url}/Stations'
params = {"Active": 1}
r = requests.get(new_url, headers=headers, params=params)
df = pd.DataFrame(r.json()['data'])
df

,stationId,stationName,latitude,longitude,utmEast_Z33,utmNorth_Z33,masl,riverName,councilNumber,councilName,...,culQ5,culQ10,culQ20,culQ50,culHm,culH5,culH10,culH20,culH50,seriesList
0,1.10.0,Skotberg bru,59.20959,11.69155,311128,6568077,114,Haldenvassdraget,3124,Aremark,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
1,1.14.0,Brekke,59.14894,11.55823,303173,6561715,118,Haldenvassdraget,3101,Halden,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
2,1.15.0,Femsjø,59.13015,11.48516,298887,6559841,81,Haldenvassdraget,3101,Halden,...,NaN,NaN,NaN,NaN,79.5405,79.6792,79.8333,80.0008,80.2505,"[{'parameterName': 'Vannstand', 'parameter': 1..."
3,1.167.0,Skulerudvatn,59.66887,11.54892,305644,6619589,118,Haldenvassdraget,3226,Aurskog-Høland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
4,1.198.0,Berg,59.92993,11.40768,299271,6649056,177,Riserelva,3226,Aurskog-Høland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4878,99.5.0,Heimste Vikvatn,62.12556,7.52601,110769,6910655,1319,Rødøla,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
4879,99.6.0,Fetvatn,62.13471,7.45939,107429,6912072,1052,Fetvasselva,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
4880,99.7.0,Heimste Veltdalsvatn,62.15934,7.71728,121122,6913264,1174,Rødalselva,3433,Skjåk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
4881,99.8.0,Viavatn,62.10119,7.39499,103649,6908749,1001,Tafjordvassdraget,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."
4882,99.9.0,Slettdalsvatn,62.12843,7.38108,103284,6911854,906,Tafjordvassdraget,1578,Fjord,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'parameterName': 'Vannstand', 'parameter': 1..."

In [64]:
new_url = f'{url}/Stations'
params = {"Active": 1}
r = requests.get(new_url, headers=headers, params=params)
columns = ['stationId', 'stationName', 'latitude', 'longitude', 'councilName', 'countyName', 'owner']
df = pd.DataFrame(r.json()['data'])[columns]
df.rename(columns={'stationId': 'id', 'stationName': 'shortName', 'councilName': 'municipality', 'countyName': 'county', 'owner': 'stationHolders'}, inplace=True)
df['name'] = df['shortName']
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.longitude, df.latitude), crs='EPSG:4326')
gdf.drop(columns=['latitude', 'longitude'], inplace=True)
gdf

,id,shortName,municipality,county,stationHolders,name,geometry
0,1.10.0,Skotberg bru,Aremark,Østfold,,Skotberg bru,POINT (11.69155 59.20959)
1,1.14.0,Brekke,Halden,Østfold,,Brekke,POINT (11.55823 59.14894)
2,1.15.0,Femsjø,Halden,Østfold,HALDENVASSDRAGETS BRUKSEIERFORENING,Femsjø,POINT (11.48516 59.13015)
3,1.167.0,Skulerudvatn,Aurskog-Høland,Akershus,,Skulerudvatn,POINT (11.54892 59.66887)
4,1.198.0,Berg,Aurskog-Høland,Akershus,,Berg,POINT (11.40768 59.92993)
...,...,...,...,...,...,...,...
4878,99.5.0,Heimste Vikvatn,Fjord,Møre og Romsdal,TAFJORD KRAFTPRODUKSJON AS,Heimste Vikvatn,POINT (7.52601 62.12556)
4879,99.6.0,Fetvatn,Fjord,Møre og Romsdal,TAFJORD KRAFTPRODUKSJON AS,Fetvatn,POINT (7.45939 62.13471)
4880,99.7.0,Heimste Veltdalsvatn,Skjåk,Innlandet,TAFJORD KRAFTPRODUKSJON AS,Heimste Veltdalsvatn,POINT (7.71728 62.15934)
4881,99.8.0,Viavatn,Fjord,Møre og Romsdal,TAFJORD KRAFTPRODUKSJON AS,Viavatn,POINT (7.39499 62.10119)
4882,99.9.0,Slettdalsvatn,Fjord,Møre og Romsdal,TAFJORD KRAFTPRODUKSJON AS,Slettdalsvatn,POINT (7.38108 62.12843)

In [14]:
start_time, end_time = '2026-01-01T00:00:00Z', '2026-02-01T00:00:00Z'
NVE_codes = {
    'precipitation': 0, 'temperature': 17, 'short_wave_radiation': 8, 
    'long_wave_radiation': 9, 'wind_speed': 15, 'humidity': 2, 'pressure': 4
}
obs_url, weather_df = f'{url}/Observations', pd.DataFrame()
weather_df['time'] = pd.date_range(start=start_time, end=end_time, freq='H').strftime('%Y-%m-%d %H:%M:%S')
observations = ['precipitation', 'temperature', 'short_wave_radiation',
            'long_wave_radiation', 'wind_speed', 'humidity', 'pressure']
for obs in observations:
    params = {
        "StationId": '103.83.0', "Parameter": NVE_codes[obs], 
        "ResolutionTime": 60, "ReferenceTime": f"{start_time}/{end_time}"
    }
    response = requests.request("GET", url, params=params, headers=headers)
    if response.status_code == 200 and response.json()['data']:
        temp_df = pd.DataFrame(response.json()['data'][0]['observations'])[['time', 'value']]
        temp_df.rename(columns={'value': obs}, inplace=True)
        weather_df = weather_df.merge(temp_df, how='left', on='time')
    else:
        weather_df[obs] = None
        continue
weather_df

,time,precipitation,temperature,short_wave_radiation,long_wave_radiation,wind_speed,humidity,pressure
0,2026-01-01 00:00:00,None,None,None,None,None,None,None
1,2026-01-01 01:00:00,None,None,None,None,None,None,None
2,2026-01-01 02:00:00,None,None,None,None,None,None,None
3,2026-01-01 03:00:00,None,None,None,None,None,None,None
4,2026-01-01 04:00:00,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...
740,2026-01-31 20:00:00,None,None,None,None,None,None,None
741,2026-01-31 21:00:00,None,None,None,None,None,None,None
742,2026-01-31 22:00:00,None,None,None,None,None,None,None
743,2026-01-31 23:00:00,None,None,None,None,None,None,None
744,2026-02-01 00:00:00,None,None,None,None,None,None,None

In [48]:
obs.json()['data'][0]['observations']

[{'time': '2026-01-01T00:00:00Z',
  'value': 79.04137,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T01:00:00Z',
  'value': 79.03912,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T02:00:00Z',
  'value': 79.04175,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T03:00:00Z',
  'value': 79.03838,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T04:00:00Z',
  'value': 79.03587,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T05:00:00Z',
  'value': 79.03313,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T06:00:00Z',
  'value': 79.03125,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T07:00:00Z',
  'value': 79.03075,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T08:00:00Z',
  'value': 79.029,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T09:00:00Z',
  'value': 79.02724,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T10:00:00Z',
  'value': 79.02676,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T11:00:00Z',
  'value': 79.02525,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T12:00:00Z',
  'value': 79.0245,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T13:00:00Z',
  'value': 79.0215,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T14:00:00Z',
  'value': 79.02051,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T15:00:00Z',
  'value': 79.01725,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T16:00:00Z',
  'value': 79.01637,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T17:00:00Z',
  'value': 79.02126,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T18:00:00Z',
  'value': 79.01199,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T19:00:00Z',
  'value': 79.00649,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T20:00:00Z',
  'value': 79.00525,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T21:00:00Z',
  'value': 79.0055,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T22:00:00Z',
  'value': 79.00313,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-01T23:00:00Z',
  'value': 79.00125,
  'correction': 0,
  'quality': 1},
 {'time': '2026-01-02T00:00:00Z',
  'value': 79.0005,
  'correction': 0,
  'quality': 1}]

In [ ]:
start, end = '2025-01-01 00:00:00', '2025-01-30 23:00:00'
start_time = datetime.strptime(start, '%Y-%m-%d %H:%M:%S')
end_time = datetime.strptime(end, '%Y-%m-%d %H:%M:%S')

In [10]:
start_time, end_time

(datetime.datetime(2025, 1, 1, 0, 0), datetime.datetime(2025, 1, 30, 23, 0))

In [ ]:
time = pd.date_range("2025-01-01", "2025-12-31 23:00", freq="H")
df = pd.DataFrame({
    "datetime": time,
    "precip_mm": np.round(np.random.gamma(1.5, 1.0, len(time)), 3),
    "temp_C": np.round(5 + 10*np.sin(2*np.pi*(time.dayofyear/365)), 3),
    "shortwave_Wm2": np.round(np.clip(500*np.sin(2*np.pi*(time.hour/24)), 0, None), 3),
    "longwave_Wm2": np.round(np.random.uniform(300, 420, len(time)), 3),
    "wind_mps": np.round(np.random.uniform(4, 10, len(time)), 3),
    "relhum_pct": np.round(np.random.uniform(70, 95, len(time)), 3),
    "pressure": np.round(np.random.uniform(980, 1020, len(time)), 3)
})
df

,datetime,precip_mm,temp_C,shortwave_Wm2,longwave_Wm2,wind_mps,relhum_pct,pressure
0,2025-01-01 00:00:00,2.447,5.172,0.000,320.125,7.620,86.733,1009.946
1,2025-01-01 01:00:00,2.383,5.172,129.410,384.656,7.993,74.095,987.605
2,2025-01-01 02:00:00,3.192,5.172,250.000,384.239,8.049,70.175,997.114
3,2025-01-01 03:00:00,0.759,5.172,353.553,364.490,7.289,87.534,988.409
4,2025-01-01 04:00:00,1.788,5.172,433.013,322.710,8.959,91.852,1013.289
...,...,...,...,...,...,...,...,...
8755,2025-12-31 19:00:00,1.529,5.000,0.000,343.680,5.803,71.896,990.648
8756,2025-12-31 20:00:00,0.724,5.000,0.000,301.795,9.012,93.424,1017.078
8757,2025-12-31 21:00:00,0.415,5.000,0.000,378.202,9.810,85.269,1017.871
8758,2025-12-31 22:00:00,1.135,5.000,0.000,360.407,9.215,84.581,1012.472
8759,2025-12-31 23:00:00,1.438,5.000,0.000,300.634,7.237,72.802,987.983

In [8]:
df.to_csv("alesund_weather.csv", index=False)